// lib/debug/policy_debug_screen.dart
// ⚠️  REMOVE THIS FILE BEFORE PRODUCTION RELEASE.

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class PolicyDebugScreen extends StatefulWidget {
  const PolicyDebugScreen({super.key});

  @override
  State<PolicyDebugScreen> createState() => _PolicyDebugScreenState();
}

class _PolicyDebugScreenState extends State<PolicyDebugScreen>
    with SingleTickerProviderStateMixin {
  final _supabase = Supabase.instance.client;
  late final TabController _tabController;

  // Tab 1: Policy tests
  final List<_TestResult> _results = [];
  bool _running = false;

  // Tab 2: Schema audit
  List<_TableAudit> _auditResults = [];
  bool _auditRunning = false;
  String _sqlScript = '';

  String get _uid => _supabase.auth.currentUser?.id ?? '';
  String get _email => _supabase.auth.currentUser?.email ?? '';
  String get _role =>
      _supabase.auth.currentUser?.userMetadata?['role'] ?? 'unknown';

  // Complete map of tables + columns actually used across all dart files
  // Generated by scanning lib/**/*.dart
  static const Map<String, List<String>> _usedSchema = {
    'profiles': ['id','role','email','full_name','phone','phone_number','avatar_url',
      'hospital_id','blood_group','height_cm','bio','zego_uid','is_verified',
      'license_number','allow_newsletters','allow_research'],
    'bookings': ['id','status','patient_id','provider_id','hospital_id',
      'appointment_date','appointment_time','lab_category','amount',
      'consultation_fee','platform_fee','queue_number','staff_id',
      'user_id','test_id','file_name','created_at'],
    'staff': ['id','email','role','hospital_id','assigned_lab','avatar_url'],
    'availability_slots': ['id','provider_id','date','start_time','end_time',
      'slot_type','appointment_date','appointment_time','created_at'],
    'medical_records': ['id','patient_id','provider_id','file_name','file_url','provider_role',
      'appointment_id','appointment_date','created_at'],
    'lab_appointments': ['id','user_id','patient_id','professional_id',
      'hospital_id','status','appointment_date','appointment_time',
      'total_amount','created_at'],
    'insurance_plans': ['id','hospital_id','name','price','coverage_amount','created_at'],
    'insurance_subscriptions': ['id','patient_id','hospital_id',
      'amount_paid','claim_amount','created_at'],
    'lab_tests': ['id','provider_id','hospital_id','name','price','created_at'],
    'staff_pairings': ['id','doctor_id','nurse_id','hospital_id','staff_id'],
    'nurse_staff_unified': ['nurse_id','assigned_doctor_id','doctor_id',
      'nurse_email','nurse_name'],
    'staff_queues': ['id','staff_id','provider_id','date'],
    'staff_assignments_view': ['nurse_email','doctor_id','hospital_id','nurse_name'],
    'patient_vitals': ['id','patient_id','user_id','created_at'],
    'call_reviews': ['id','doctor_id','patient_id','caller_id','receiver_id',
      'rating','review_text','duration_seconds','status','created_at'],
    'hospitals': ['id','name','email','location','avatar_url','rating'],
    'user_consents': ['id','user_id'],
    'reviews': ['id','doctor_id','user_id'],
    'provider_documents': ['id','provider_id','name','verification_status'],
    'platform_transactions': ['id','hospital_id','user_id','status','created_at'],
    'blood_inventory': ['id','hospital_id','blood_group','blood_type'],
    'deletion_requests': ['id','user_id'],
    'doctor_schedules': ['id','nurse_id','assigned_doctor_id'],
    'hospital_staff_unified': ['id','hospital_id'],
    'appointments': ['id'],
    'notifications': ['id','user_id','created_at'],
    'revenue_stats': ['hospital_id','created_at'],
    'call_sessions': ['id','caller_id','receiver_id','hospital_id','status'],
    'consultation_requests': ['id'],
    'lab_offers': ['id'],
  };

  // Tables that are views — cannot be dropped
  static const Set<String> _views = {
    'nurse_staff_unified',
    'staff_assignments_view',
    'hospital_staff_unified',
    'revenue_stats',
  };

  // Low-usage tables flagged for review
  static const List<_LowUsage> _lowUsageTables = [
    _LowUsage('appointments', 'Only used in queue_widget_service for id. May overlap with bookings.'),
    _LowUsage('call_sessions', 'Only in policy debug screen — not found in main app flow.'),
    _LowUsage('consultation_requests', 'Only 1 reference found across all dart files.'),
    _LowUsage('lab_offers', 'Only 1 reference found across all dart files.'),
    _LowUsage('doctor_schedules', 'Only in policy debug screen — not in any real screen.'),
  ];

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);
    _runAllTests();
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  // ══════════════════════════════════════════════
  // TAB 1 — POLICY TESTS
  // ══════════════════════════════════════════════

  Future<void> _runAllTests() async {
    if (_uid.isEmpty) {
      setState(() => _results.add(_TestResult(
        table: 'AUTH', screen: 'All screens', roleLabel: 'ALL',
        status: _Status.fail, message: 'Not logged in — cannot test policies',
      )));
      return;
    }
    setState(() { _running = true; _results.clear(); });

    // ── SHARED: every logged-in role needs these ──────────────────────────
    await _test(
      table: 'profiles (own)',
      screen: 'patient_settings / professional_setting',
      roleLabel: 'ALL',
      query: () => _supabase.from('profiles').select('id,role').eq('id', _uid).maybeSingle(),
    );
    await _test(
      table: 'profiles (others)',
      screen: 'consultation_search',
      roleLabel: 'ALL',
      query: () => _supabase.from('profiles').select('id,role').neq('id', _uid).limit(1),
    );
    await _test(
      table: 'hospitals',
      screen: 'consultation_search',
      roleLabel: 'ALL',
      query: () => _supabase.from('hospitals').select('id,name').limit(3),
    );
    await _test(
      table: 'notifications',
      screen: 'notification_screen',
      roleLabel: 'ALL',
      query: () => _supabase.from('notifications').select('id,user_id').limit(3),
    );
    await _test(
      table: 'user_consents',
      screen: 'registration_page',
      roleLabel: 'ALL',
      query: () => _supabase.from('user_consents').select('id,user_id').eq('user_id', _uid).limit(1),
    );
    await _testStorage(bucket: 'avatars', screen: 'profile settings', path: '$_uid/', roleLabel: 'ALL');
    await _testRpc(name: 'get_unread_notification_count', screen: 'patient_home', params: {}, roleLabel: 'ALL');
    await _testRpc(name: 'mark_all_notifications_read', screen: 'notification_screen', params: {}, roleLabel: 'ALL');

    // ── PATIENT-ONLY ──────────────────────────────────────────────────────
    if (_role == 'patient' || _role == 'unknown') {
      await _test(
        table: 'bookings (patient)',
        screen: 'all_bookings',
        roleLabel: 'patient',
        query: () => _supabase.from('bookings').select('id,status,patient_id').eq('patient_id', _uid).limit(3),
      );
      await _test(
        table: 'medical_records (own)',
        screen: 'medical_vault',
        roleLabel: 'patient',
        query: () => _supabase.from('medical_records').select('id,patient_id,file_name').eq('patient_id', _uid).limit(3),
      );
      await _test(
        table: 'patient_vitals (own)',
        screen: 'medical_vault',
        roleLabel: 'patient',
        query: () => _supabase.from('patient_vitals').select('id,patient_id').eq('patient_id', _uid).limit(3),
      );
      await _test(
        table: 'insurance_subscriptions (own)',
        screen: 'insurance_screen',
        roleLabel: 'patient',
        query: () => _supabase.from('insurance_subscriptions').select('id,patient_id').eq('patient_id', _uid).limit(3),
      );
      await _test(
        table: 'insurance_plans',
        screen: 'plan_details_screen',
        roleLabel: 'patient',
        query: () => _supabase.from('insurance_plans').select('id,hospital_id').limit(3),
      );
      await _test(
        table: 'lab_appointments (patient)',
        screen: 'lab_screen',
        roleLabel: 'patient',
        query: () => _supabase.from('lab_appointments').select('id,user_id,status').eq('user_id', _uid).limit(3),
      );
      await _test(
        table: 'deletion_requests (own)',
        screen: 'patient_settings',
        roleLabel: 'patient',
        query: () => _supabase.from('deletion_requests').select('id,user_id').eq('user_id', _uid).limit(1),
      );
      await _test(
        table: 'availability_slots',
        screen: 'consultation_booking',
        roleLabel: 'patient',
        query: () => _supabase.from('availability_slots').select('id,provider_id,date').limit(3),
      );
      await _test(
        table: 'reviews',
        screen: 'doctor_detail',
        roleLabel: 'patient',
        query: () => _supabase.from('reviews').select('id,doctor_id,user_id').limit(3),
      );
      await _testStorage(bucket: 'medical_vault', screen: 'medical_vault', path: '$_uid/', roleLabel: 'patient');
      await _testStorage(bucket: 'insurance_vault', screen: 'coverage_screen', path: '$_uid/', roleLabel: 'patient');
      await _testRpc(
        name: 'calculate_booking_fee',
        screen: 'consultation_payment_screen',
        params: {'p_hospital_id': _uid, 'p_booking_type': 'physical', 'p_base_amount': 500},
        roleLabel: 'patient',
      );
      await _testRpc(
        name: 'book_appointment_atomic',
        screen: 'consultation_payment_screen',
        params: {
          'p_provider_id': _uid, 'p_patient_id': _uid, 'p_hospital_id': _uid,
          'p_date': DateTime.now().toIso8601String().substring(0, 10),
          'p_time': '10:00', 'p_type': 'physical', 'p_fee': 500,
          'p_patient_zego_uid': 'debug-patient-zego',
          'p_provider_zego_uid': 'debug-provider-zego',
          'p_room_id': 'room_debug_provider_debug_patient',
          'p_idempotency_key': 'debug-test-key',
        },
        roleLabel: 'patient',
      );
    }

    // ── DOCTOR / PROFESSIONAL ─────────────────────────────────────────────
    if (_role == 'doctor' || _role == 'unknown') {
      await _test(
        table: 'bookings (provider)',
        screen: 'queue_tab',
        roleLabel: 'doctor',
        query: () => _supabase.from('bookings').select('id,status,provider_id').eq('provider_id', _uid).limit(3),
      );
      await _test(
        table: 'medical_records (patients under me)',
        screen: 'shared_widgets',
        roleLabel: 'doctor',
        query: () => _supabase.from('medical_records').select('id,patient_id,file_name').limit(3),
      );
      await _test(
        table: 'patient_vitals (patients)',
        screen: 'shared_widgets',
        roleLabel: 'doctor',
        query: () => _supabase.from('patient_vitals').select('id,patient_id').limit(3),
      );
      await _test(
        table: 'staff',
        screen: 'health_vault_screen',
        roleLabel: 'doctor',
        query: () => _supabase.from('staff').select('id,email,role').eq('id', _uid).limit(1),
      );
      await _test(
        table: 'staff_pairings',
        screen: 'doctor_setting',
        roleLabel: 'doctor',
        query: () => _supabase.from('staff_pairings').select('id,doctor_id,nurse_id').eq('doctor_id', _uid).limit(3),
      );
      await _test(
        table: 'availability_slots (own)',
        screen: 'consultation_booking',
        roleLabel: 'doctor',
        query: () => _supabase.from('availability_slots').select('id,provider_id,date').eq('provider_id', _uid).limit(3),
      );
      await _test(
        table: 'call_reviews (own)',
        screen: 'professional_insights',
        roleLabel: 'doctor',
        query: () => _supabase.from('call_reviews').select('id,doctor_id').eq('doctor_id', _uid).limit(3),
      );
      await _test(
        table: 'call_sessions',
        screen: 'video_call_page',
        roleLabel: 'doctor',
        query: () => _supabase.from('call_sessions').select('id,caller_id,status').limit(3),
      );
      await _test(
        table: 'nurse_staff_unified (view)',
        screen: 'health_vault_screen',
        roleLabel: 'doctor',
        query: () => _supabase.from('nurse_staff_unified').select('nurse_id,assigned_doctor_id').limit(3),
      );
      await _test(
        table: 'staff_assignments_view (view)',
        screen: 'supabase_handler',
        roleLabel: 'doctor',
        query: () => _supabase.from('staff_assignments_view').select('nurse_email,doctor_id').limit(3),
      );
      await _testStorage(bucket: 'medical_vault', screen: 'shared_widgets', path: '', roleLabel: 'doctor');
    }

    // ── HOSPITAL ADMIN ────────────────────────────────────────────────────
    if (_role == 'hospital' || _role == 'clinic' || _role == 'unknown') {
      await _test(
        table: 'platform_transactions',
        screen: 'revenue_screen',
        roleLabel: 'hospital/clinic',
        query: () => _supabase.from('platform_transactions').select('id,hospital_id').limit(3),
      );
      await _test(
        table: 'blood_inventory',
        screen: 'blood_bank',
        roleLabel: 'hospital/clinic',
        query: () => _supabase.from('blood_inventory').select('id,hospital_id,blood_type').limit(3),
      );
      await _test(
        table: 'lab_tests',
        screen: 'new_lab_test',
        roleLabel: 'hospital/clinic',
        query: () => _supabase.from('lab_tests').select('id,name,provider_id').limit(3),
      );
      await _test(
        table: 'provider_documents',
        screen: 'registration_page',
        roleLabel: 'hospital/clinic',
        query: () => _supabase.from('provider_documents').select('id,provider_id,verification_status').limit(3),
      );
      await _test(
        table: 'staff_queues',
        screen: 'queue_tab',
        roleLabel: 'hospital/clinic',
        query: () => _supabase.from('staff_queues').select('staff_id').limit(3),
      );
      await _test(
        table: 'insurance_plans (manage)',
        screen: 'insurance_screen',
        roleLabel: 'hospital/clinic',
        query: () => _supabase.from('insurance_plans').select('id,hospital_id').limit(3),
      );
    }

    setState(() => _running = false);
  }

  // ══════════════════════════════════════════════
  // TAB 2 — SCHEMA AUDIT
  // ══════════════════════════════════════════════

  Future<void> _runSchemaAudit() async {
    setState(() { _auditRunning = true; _auditResults = []; _sqlScript = ''; });

    final List<_TableAudit> audits = [];
    final StringBuffer sql = StringBuffer();
    sql.writeln('-- ═══════════════════════════════════════════════════');
    sql.writeln('-- Swasthall Schema Cleanup SQL');
    sql.writeln('-- Generated: ${DateTime.now().toIso8601String().substring(0,19)}');
    sql.writeln('-- REVIEW CAREFULLY before running in production!');
    sql.writeln('-- Uncomment a line only when you are 100% sure.');
    sql.writeln('-- ═══════════════════════════════════════════════════\n');

    for (final entry in _usedSchema.entries) {
      final tableName = entry.key;
      final usedCols = entry.value.toSet();
      final isView = _views.contains(tableName);

      try {
        final probe = await _supabase.from(tableName).select().limit(1);
        List<String> dbCols = [];
        if (probe.isNotEmpty) {
          dbCols = probe.first.keys.toList();
        }

        final unusedCols = dbCols
            .where((c) => !usedCols.contains(c))
            .where((c) => !_isSafeSystemCol(c))
            .toList();

        audits.add(_TableAudit(
          tableName: tableName,
          isView: isView,
          usedColumns: usedCols.where((c) => dbCols.contains(c)).toList(),
          allDbColumns: dbCols,
          unusedColumns: unusedCols,
          accessible: true,
        ));

        if (unusedCols.isNotEmpty && !isView) {
          sql.writeln('-- ── $tableName: ${unusedCols.length} possibly unused column(s)');
          for (final col in unusedCols) {
            sql.writeln('-- ALTER TABLE $tableName DROP COLUMN IF EXISTS "$col";');
          }
          sql.writeln();
        }
      } catch (e) {
        audits.add(_TableAudit(
          tableName: tableName, isView: isView,
          usedColumns: usedCols.toList(), allDbColumns: [],
          unusedColumns: [], accessible: false, error: e.toString(),
        ));
      }
      await Future.delayed(const Duration(milliseconds: 60));
    }

    // Low-usage tables section
    sql.writeln('\n-- ═══════════════════════════════════════════════════');
    sql.writeln('-- LOW-USAGE TABLES — Review before dropping');
    sql.writeln('-- Check FK constraints with:');
    sql.writeln('-- SELECT * FROM information_schema.referential_constraints WHERE unique_constraint_schema=\'public\';');
    sql.writeln('-- ═══════════════════════════════════════════════════\n');
    for (final t in _lowUsageTables) {
      sql.writeln('-- ${t.table}: ${t.reason}');
      sql.writeln('-- DROP TABLE IF EXISTS ${t.table} CASCADE;');
      sql.writeln();
    }

    audits.sort((a, b) {
      if (!a.accessible && b.accessible) return -1;
      if (a.accessible && !b.accessible) return 1;
      return b.unusedColumns.length.compareTo(a.unusedColumns.length);
    });

    setState(() {
      _auditResults = audits;
      _sqlScript = sql.toString();
      _auditRunning = false;
    });
  }

  bool _isSafeSystemCol(String col) =>
      {'id','created_at','updated_at','deleted_at','uuid'}.contains(col);

  // ══════════════════════════════════════════════
  // HELPERS
  // ══════════════════════════════════════════════

  Future<void> _test({
    required String table,
    required String screen,
    required String roleLabel,
    required Future<dynamic> Function() query,
  }) async {
    try {
      final r = await query();
      String msg = 'Query succeeded';
      if (r is List) { msg = 'Returned ${r.length} row(s)'; }
      else if (r is Map) { msg = 'Returned 1 row'; }
      else if (r == null) { msg = 'No matching rows (null)'; }
      setState(() => _results.add(_TestResult(table: table, screen: screen, roleLabel: roleLabel, status: _Status.pass, message: msg)));
    } on PostgrestException catch (e) {
      setState(() => _results.add(_TestResult(table: table, screen: screen, roleLabel: roleLabel, status: _Status.fail,
          message: 'DB ${e.code}: ${e.message}', hint: e.hint)));
    } catch (e) {
      setState(() => _results.add(_TestResult(table: table, screen: screen, roleLabel: roleLabel, status: _Status.fail, message: e.toString())));
    }
    await Future.delayed(const Duration(milliseconds: 80));
  }

  Future<void> _testStorage({
    required String bucket,
    required String screen,
    required String path,
    required String roleLabel,
  }) async {
    try {
      await _supabase.storage.from(bucket).list(path: path);
      setState(() => _results.add(_TestResult(table: 'storage: $bucket', screen: screen, roleLabel: roleLabel, status: _Status.pass, message: 'Accessible')));
    } catch (e) {
      final ok = e.toString().contains('404') || e.toString().contains('not found');
      setState(() => _results.add(_TestResult(table: 'storage: $bucket', screen: screen, roleLabel: roleLabel,
          status: ok ? _Status.pass : _Status.fail,
          message: ok ? 'Accessible (empty folder)' : e.toString())));
    }
    await Future.delayed(const Duration(milliseconds: 80));
  }

  Future<void> _testRpc({
    required String name,
    required String screen,
    required Map<String, dynamic> params,
    required String roleLabel,
  }) async {
    try {
      await _supabase.rpc(name, params: params);
      setState(() => _results.add(_TestResult(table: 'rpc: $name', screen: screen, roleLabel: roleLabel, status: _Status.pass, message: 'RPC callable')));
    } catch (e) {
      final isExpected = name == 'book_appointment_atomic' && e.toString().contains('debug-test-key');
      setState(() => _results.add(_TestResult(table: 'rpc: $name', screen: screen, roleLabel: roleLabel,
          status: _Status.pass,
          message: isExpected ? 'RPC callable (constraint hit as expected)' : 'Called: ${e.toString().substring(0, 60)}')));
    }
    await Future.delayed(const Duration(milliseconds: 80));
  }

  // ══════════════════════════════════════════════
  // BUILD
  // ══════════════════════════════════════════════

  @override
  Widget build(BuildContext context) {
    final failCount = _results.where((r) => r.status == _Status.fail).length;
    final passCount = _results.where((r) => r.status == _Status.pass).length;
    final issueCount = _auditResults.fold(0, (s, a) => s + a.unusedColumns.length);

    return Scaffold(
      appBar: AppBar(
        title: const Text('Dev Debug'),
        bottom: TabBar(
          controller: _tabController,
          tabs: [
            Tab(text: 'Policies ($passCount✓ $failCount✗)'),
            Tab(text: issueCount > 0 ? 'Schema ($issueCount issues)' : 'Schema'),
          ],
        ),
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: () {
              if (_tabController.index == 0) { _runAllTests(); }
              else { _runSchemaAudit(); }
            },
          ),
        ],
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          _buildPolicyTab(passCount, failCount),
          _buildSchemaTab(issueCount),
        ],
      ),
    );
  }

  Widget _buildPolicyTab(int passCount, int failCount) {
    return Column(children: [
      _InfoBanner(email: _email, role: _role, running: _running,
        leftLabel: '$passCount passed', leftColor: Colors.green,
        rightLabel: '$failCount failed', rightColor: failCount > 0 ? Colors.red : Colors.grey,
        runningText: 'Testing ${_results.length} tables...'),
      Expanded(child: ListView.builder(
        padding: const EdgeInsets.symmetric(horizontal: 12),
        itemCount: _results.length,
        itemBuilder: (ctx, i) => _ResultTile(result: _results[i]),
      )),
    ]);
  }

  Widget _buildSchemaTab(int issueCount) {
    if (_auditResults.isEmpty && !_auditRunning) {
      return Center(child: Column(mainAxisAlignment: MainAxisAlignment.center, children: [
        Icon(Icons.schema_outlined, size: 56, color: Colors.grey[300]),
        const SizedBox(height: 16),
        const Text('Tap Run to scan your database schema', style: TextStyle(color: Colors.grey)),
        const SizedBox(height: 16),
        ElevatedButton.icon(
          onPressed: _runSchemaAudit,
          icon: const Icon(Icons.play_arrow),
          label: const Text('Run Schema Audit'),
          style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF6366F1), foregroundColor: Colors.white),
        ),
      ]));
    }

    return Column(children: [
      _InfoBanner(email: _email, role: _role, running: _auditRunning,
        leftLabel: '${_auditResults.where((a) => a.accessible).length} tables scanned',
        leftColor: Colors.blue,
        rightLabel: issueCount > 0 ? '$issueCount unused cols' : 'Schema clean',
        rightColor: issueCount > 0 ? Colors.orange : Colors.green,
        runningText: 'Scanning tables...'),

      // Low usage warning card
      if (!_auditRunning && _auditResults.isNotEmpty)
        Container(
          margin: const EdgeInsets.fromLTRB(12, 0, 12, 8),
          padding: const EdgeInsets.all(10),
          decoration: BoxDecoration(
            color: Colors.red.withValues(alpha: 0.05),
            border: Border.all(color: Colors.red.withValues(alpha: 0.2)),
            borderRadius: BorderRadius.circular(8),
          ),
          child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
            const Text('⚠ Low-usage tables (candidates for removal):',
              style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: Colors.red)),
            const SizedBox(height: 6),
            ..._lowUsageTables.map((t) => Padding(
              padding: const EdgeInsets.only(bottom: 3),
              child: Text('• ${t.table} — ${t.reason}',
                style: const TextStyle(fontSize: 11, color: Colors.red)),
            )),
          ]),
        ),

      if (_sqlScript.isNotEmpty)
        Padding(
          padding: const EdgeInsets.fromLTRB(12, 0, 12, 8),
          child: SizedBox(
            width: double.infinity,
            child: OutlinedButton.icon(
              onPressed: () {
                Clipboard.setData(ClipboardData(text: _sqlScript));
                ScaffoldMessenger.of(context).showSnackBar(const SnackBar(
                  content: Text('Cleanup SQL copied to clipboard'),
                  backgroundColor: Colors.green,
                ));
              },
              icon: const Icon(Icons.copy, size: 16),
              label: const Text('Copy Cleanup SQL'),
              style: OutlinedButton.styleFrom(
                foregroundColor: const Color(0xFF6366F1),
                side: const BorderSide(color: Color(0xFF6366F1)),
              ),
            ),
          ),
        ),

      Expanded(child: ListView.builder(
        padding: const EdgeInsets.symmetric(horizontal: 12),
        itemCount: _auditResults.length,
        itemBuilder: (ctx, i) => _AuditTile(audit: _auditResults[i]),
      )),
    ]);
  }
}

// ══════════════════════════════════════════════
// WIDGETS
// ══════════════════════════════════════════════

class _InfoBanner extends StatelessWidget {
  final String email, role, leftLabel, rightLabel, runningText;
  final Color leftColor, rightColor;
  final bool running;
  const _InfoBanner({required this.email, required this.role,
    required this.running, required this.leftLabel, required this.leftColor,
    required this.rightLabel, required this.rightColor, required this.runningText});

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.all(12),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: Theme.of(context).colorScheme.surfaceContainerHighest,
        borderRadius: BorderRadius.circular(10),
      ),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Row(children: [
          Text('Email: ', style: TextStyle(fontSize: 12, color: Theme.of(context).colorScheme.onSurface.withValues(alpha: 0.6))),
          Expanded(child: Text(email, style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w500), overflow: TextOverflow.ellipsis)),
        ]),
        const SizedBox(height: 2),
        Row(children: [
          Text('Role: ', style: TextStyle(fontSize: 12, color: Theme.of(context).colorScheme.onSurface.withValues(alpha: 0.6))),
          Text(role, style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w500)),
        ]),
        const SizedBox(height: 6),
        if (running)
          Row(children: [
            const SizedBox(width: 12, height: 12, child: CircularProgressIndicator(strokeWidth: 2)),
            const SizedBox(width: 8),
            Text(runningText, style: const TextStyle(fontSize: 12)),
          ])
        else
          Row(children: [
            _Chip(label: leftLabel, color: leftColor),
            const SizedBox(width: 8),
            _Chip(label: rightLabel, color: rightColor),
          ]),
      ]),
    );
  }
}

class _AuditTile extends StatelessWidget {
  final _TableAudit audit;
  const _AuditTile({required this.audit});

  @override
  Widget build(BuildContext context) {
    final hasIssues = audit.unusedColumns.isNotEmpty;
    final color = !audit.accessible ? Colors.red : hasIssues ? Colors.orange : Colors.green;

    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.05),
        border: Border.all(color: color.withValues(alpha: 0.3), width: 0.5),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Theme(
        data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
        child: ExpansionTile(
          tilePadding: const EdgeInsets.symmetric(horizontal: 10, vertical: 2),
          leading: Icon(!audit.accessible ? Icons.error_outline :
            hasIssues ? Icons.warning_amber_outlined : Icons.check_circle_outline,
            size: 18, color: color),
          title: Row(children: [
            Expanded(child: Text(
              '${audit.tableName}${audit.isView ? ' (view)' : ''}',
              style: TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: color),
            )),
            if (hasIssues)
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                decoration: BoxDecoration(color: Colors.orange.withValues(alpha: 0.15), borderRadius: BorderRadius.circular(10)),
                child: Text('${audit.unusedColumns.length} unused',
                  style: const TextStyle(fontSize: 10, color: Colors.orange, fontWeight: FontWeight.bold)),
              ),
          ]),
          subtitle: audit.accessible
            ? Text('${audit.allDbColumns.length} DB cols · ${audit.usedColumns.length} used in app',
                style: const TextStyle(fontSize: 10, color: Colors.grey))
            : Text(audit.error ?? 'Not accessible',
                style: const TextStyle(fontSize: 10, color: Colors.red)),
          children: [
            Padding(
              padding: const EdgeInsets.fromLTRB(16, 0, 16, 12),
              child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
                if (audit.unusedColumns.isNotEmpty) ...[
                  const Text('Possibly unused:', style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: Colors.orange)),
                  const SizedBox(height: 4),
                  Wrap(spacing: 6, runSpacing: 4,
                    children: audit.unusedColumns.map((col) => Container(
                      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                      decoration: BoxDecoration(
                        color: Colors.orange.withValues(alpha: 0.1),
                        borderRadius: BorderRadius.circular(4),
                        border: Border.all(color: Colors.orange.withValues(alpha: 0.3)),
                      ),
                      child: Text(col, style: const TextStyle(fontSize: 11, fontFamily: 'monospace')),
                    )).toList(),
                  ),
                  const SizedBox(height: 10),
                ],
                if (audit.usedColumns.isNotEmpty) ...[
                  const Text('Used in app:', style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: Colors.green)),
                  const SizedBox(height: 4),
                  Wrap(spacing: 6, runSpacing: 4,
                    children: audit.usedColumns.map((col) => Container(
                      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                      decoration: BoxDecoration(color: Colors.green.withValues(alpha: 0.08), borderRadius: BorderRadius.circular(4)),
                      child: Text(col, style: const TextStyle(fontSize: 11, fontFamily: 'monospace', color: Colors.green)),
                    )).toList(),
                  ),
                ],
              ]),
            ),
          ],
        ),
      ),
    );
  }
}

class _ResultTile extends StatelessWidget {
  final _TestResult result;
  const _ResultTile({required this.result});
  @override
  Widget build(BuildContext context) {
    final isPass = result.status == _Status.pass;
    final color = isPass ? Colors.green : Colors.red;

    Color roleBadgeColor = Colors.blueGrey;
    if (result.roleLabel == 'patient') {
      roleBadgeColor = const Color(0xFF6366F1);
    } else if (result.roleLabel == 'doctor') {
      roleBadgeColor = const Color(0xFF0EA5E9);
    } else if (result.roleLabel == 'hospital/clinic') {
      roleBadgeColor = const Color(0xFFEC4899);
    } else if (result.roleLabel == 'ALL') {
      roleBadgeColor = Colors.grey;
    }

    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.all(10),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.06),
        border: Border.all(color: color.withValues(alpha: 0.3), width: 0.5),
        borderRadius: BorderRadius.circular(8),
      ),
      child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [
        Row(children: [
          Icon(isPass ? Icons.check_circle_outline : Icons.error_outline, size: 14, color: color),
          const SizedBox(width: 6),
          Expanded(child: Text(result.table, style: TextStyle(fontSize: 13, fontWeight: FontWeight.w600, color: color))),
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 2),
            decoration: BoxDecoration(
              color: roleBadgeColor.withValues(alpha: 0.12),
              borderRadius: BorderRadius.circular(8),
              border: Border.all(color: roleBadgeColor.withValues(alpha: 0.3)),
            ),
            child: Text(result.roleLabel,
              style: TextStyle(fontSize: 10, color: roleBadgeColor, fontWeight: FontWeight.w600)),
          ),
        ]),
        const SizedBox(height: 3),
        Text('Screen: ${result.screen}', style: TextStyle(fontSize: 11, color: Theme.of(context).colorScheme.onSurface.withValues(alpha: 0.5))),
        const SizedBox(height: 3),
        Text(result.message, style: TextStyle(fontSize: 12, color: isPass ? Colors.green[800] : Colors.red[800])),
        if (result.hint != null)
          Padding(padding: const EdgeInsets.only(top: 2),
            child: Text('Hint: ${result.hint}', style: TextStyle(fontSize: 11, color: Colors.orange[800]))),
      ]),
    );
  }
}

class _Chip extends StatelessWidget {
  final String label;
  final Color color;
  const _Chip({required this.label, required this.color});
  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
      decoration: BoxDecoration(color: color.withValues(alpha: 0.1), borderRadius: BorderRadius.circular(10)),
      child: Text(label, style: TextStyle(fontSize: 11, color: color, fontWeight: FontWeight.w500)),
    );
  }
}

// ══════════════════════════════════════════════
// MODELS
// ══════════════════════════════════════════════

class _TableAudit {
  final String tableName;
  final bool isView, accessible;
  final List<String> usedColumns, allDbColumns, unusedColumns;
  final String? error;
  const _TableAudit({required this.tableName, required this.isView,
    required this.usedColumns, required this.allDbColumns,
    required this.unusedColumns, required this.accessible, this.error});
}

class _LowUsage {
  final String table, reason;
  const _LowUsage(this.table, this.reason);
}

enum _Status { pass, fail }

class _TestResult {
  final String table, screen, message, roleLabel;
  final _Status status;
  final String? hint;
  const _TestResult({required this.table, required this.screen,
    required this.status, required this.message, required this.roleLabel, this.hint});
}