const List<String> healthTips = [
  "Stay hydrated by drinking at least 8 glasses of water a day.",
  "Aim for 7-8 hours of sleep each night to allow your body to rest and recover.",
  "Incorporate at least 30 minutes of moderate physical activity into your daily routine.",
  "Eat a balanced diet rich in fruits, vegetables, whole grains, and lean proteins.",
  "Practice mindfulness or meditation to reduce stress and improve mental well-being.",
  "Wash your hands frequently with soap and water to prevent the spread of germs.",
  "Limit your intake of processed foods and added sugars.",
  "Take regular breaks from screens to reduce eye strain.",
  "Don't skip breakfast; it kickstarts your metabolism for the day.",
  "Maintain a healthy weight to lower your risk of chronic diseases.",
  "Wear sunscreen daily to protect your skin from harmful UV rays.",
  "Get regular health check-ups and screenings.",
  "Floss daily to maintain good oral hygiene and prevent gum disease.",
  "Limit alcohol consumption to moderate levels.",
  "Avoid smoking and exposure to secondhand smoke.",
  "Stand up and stretch every hour if you have a desk job.",
  "Include strength training exercises in your routine at least twice a week.",
  "Choose whole foods over supplements whenever possible.",
  "Practice deep breathing exercises to help manage anxiety.",
  "Keep your vaccinations up to date.",
  "Eat slowly and mindfully to aid digestion and prevent overeating.",
  "Build strong social connections for better emotional health.",
  "Listen to your body and rest when you feel tired or unwell.",
  "Keep a positive attitude; optimism is linked to better health outcomes.",
  "Read food labels to make informed choices about what you eat.",
  "Find a physical activity you enjoy to make exercise feel less like a chore.",
  "Keep healthy snacks like nuts or fruit readily available.",
  "Manage your blood pressure by reducing sodium intake.",
  "Seek professional help if you are struggling with your mental health.",
  "Laugh often; it's a great stress reliever and boosts your immune system."
];
